C +
      real    adj_AJ,tau_AJ,dpktAJ,dqv_AJ,dqw_AJ,dqi_AJ,
     .        drr_AJ,dsn_AJ,rainAJ,hANAAJ,rANAAJ
C +
      common /hy_cnv/ adj_AJ(klon     ),tau_AJ(klon     ),
     .                dpktAJ(klon,klev),dqv_AJ(klon,klev),
     .                dqw_AJ(klon,klev),dqi_AJ(klon,klev),
     .                drr_AJ(klon     ),dsn_AJ(klon     ),
     .                rainAJ(klon     ),hANAAJ(klon     ),
     .                rANAAJ
C +
